# Generated by dev/gen_streamers.jl from ROOT 6.40.02.
# Do not edit: regenerate instead.
#
# ROOT's description of its own classes, which a file this package writes
# carries so that a reader with no dictionary can still decode it. See
# `streamer_info` for how these are selected when writing.

function _builtin_streamers()
    v = Any[]

    push!(
        v,
        TStreamerInfo(
            "ROOT::TIOFeatures",
            1;
            checksum=0x1aa12f10,
            elems=[TStreamerBasicType(_el("fIOBits", "unsigned char", 11, 1, ""))],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArray",
            1;
            checksum=0x007021b2,
            elems=[TStreamerBasicType(_el("fN", "int", 6, 4, "Number of array elements"))],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArrayC",
            1;
            checksum=0xae879936,
            elems=[
                TStreamerBase(
                    _el(
                        "TArray",
                        "BASE",
                        0,
                        0,
                        "Abstract array base class";
                        maxidx=(0, 7348658, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicPointer(
                    _el("fArray", "char*", 41, 1, "[fN] Array of fN chars"),
                    1,
                    "fN",
                    "TArray",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArrayD",
            1;
            checksum=0x7139ef34,
            elems=[
                TStreamerBase(
                    _el(
                        "TArray",
                        "BASE",
                        0,
                        0,
                        "Abstract array base class";
                        maxidx=(0, 7348658, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicPointer(
                    _el("fArray", "double*", 48, 8, "[fN] Array of fN doubles"),
                    1,
                    "fN",
                    "TArray",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArrayF",
            1;
            checksum=0x5a0bf6f1,
            elems=[
                TStreamerBase(
                    _el(
                        "TArray",
                        "BASE",
                        0,
                        0,
                        "Abstract array base class";
                        maxidx=(0, 7348658, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicPointer(
                    _el("fArray", "float*", 45, 4, "[fN] Array of fN floats"),
                    1,
                    "fN",
                    "TArray",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArrayI",
            1;
            checksum=0xd9d571c7,
            elems=[
                TStreamerBase(
                    _el(
                        "TArray",
                        "BASE",
                        0,
                        0,
                        "Abstract array base class";
                        maxidx=(0, 7348658, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicPointer(
                    _el("fArray", "int*", 43, 4, "[fN] Array of fN 32 bit integers"),
                    1,
                    "fN",
                    "TArray",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArrayL",
            1;
            checksum=0xfcfcb489,
            elems=[
                TStreamerBase(
                    _el(
                        "TArray",
                        "BASE",
                        0,
                        0,
                        "Abstract array base class";
                        maxidx=(0, 7348658, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicPointer(
                    _el("fArray", "long*", 44, 8, "[fN] Array of fN longs"),
                    1,
                    "fN",
                    "TArray",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArrayL64",
            1;
            checksum=0x18e70794,
            elems=[
                TStreamerBase(
                    _el(
                        "TArray",
                        "BASE",
                        0,
                        0,
                        "Abstract array base class";
                        maxidx=(0, 7348658, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicPointer(
                    _el("fArray", "Long64_t*", 56, 8, "[fN] Array of fN long64s"),
                    1,
                    "fN",
                    "TArray",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TArrayS",
            1;
            checksum=0x035c9314,
            elems=[
                TStreamerBase(
                    _el(
                        "TArray",
                        "BASE",
                        0,
                        0,
                        "Abstract array base class";
                        maxidx=(0, 7348658, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicPointer(
                    _el("fArray", "short*", 42, 2, "[fN] Array of fN shorts"),
                    1,
                    "fN",
                    "TArray",
                ),
            ],
        ),
    )

    push!(v, TStreamerInfo("TAtt3D", 1; checksum=0x0000757a, elems=[]))

    push!(
        v,
        TStreamerInfo(
            "TAttAxis",
            4;
            checksum=0x5c6fff3e,
            elems=[
                TStreamerBasicType(
                    _el(
                        "fNdivisions",
                        "int",
                        3,
                        4,
                        "Number of divisions(10000*n3 + 100*n2 + n1)",
                    ),
                ),
                TStreamerBasicType(
                    _el("fAxisColor", "short", 2, 2, "Color of the line axis")
                ),
                TStreamerBasicType(_el("fLabelColor", "short", 2, 2, "Color of labels")),
                TStreamerBasicType(_el("fLabelFont", "short", 2, 2, "Font for labels")),
                TStreamerBasicType(_el("fLabelOffset", "float", 5, 4, "Offset of labels")),
                TStreamerBasicType(_el("fLabelSize", "float", 5, 4, "Size of labels")),
                TStreamerBasicType(
                    _el("fTickLength", "float", 5, 4, "Length of tick marks")
                ),
                TStreamerBasicType(
                    _el("fTitleOffset", "float", 5, 4, "Offset of axis title")
                ),
                TStreamerBasicType(_el("fTitleSize", "float", 5, 4, "Size of axis title")),
                TStreamerBasicType(
                    _el("fTitleColor", "short", 2, 2, "Color of axis title")
                ),
                TStreamerBasicType(_el("fTitleFont", "short", 2, 2, "Font for axis title")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TAttFill",
            2;
            checksum=0xffd92a92,
            elems=[
                TStreamerBasicType(_el("fFillColor", "short", 2, 2, "Fill area color")),
                TStreamerBasicType(_el("fFillStyle", "short", 2, 2, "Fill area style")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TAttLine",
            2;
            checksum=0x94074549,
            elems=[
                TStreamerBasicType(_el("fLineColor", "short", 2, 2, "Line color")),
                TStreamerBasicType(_el("fLineStyle", "short", 2, 2, "Line style")),
                TStreamerBasicType(_el("fLineWidth", "short", 2, 2, "Line width")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TAttMarker",
            3;
            checksum=0x291d8bec,
            elems=[
                TStreamerBasicType(_el("fMarkerColor", "short", 2, 2, "Marker color")),
                TStreamerBasicType(_el("fMarkerStyle", "short", 2, 2, "Marker style")),
                TStreamerBasicType(_el("fMarkerSize", "float", 5, 4, "Marker size")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TAxis",
            10;
            checksum=0x5a496e70,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBase(
                    _el(
                        "TAttAxis",
                        "BASE",
                        0,
                        0,
                        "Axis attributes";
                        maxidx=(0, 1550843710, 0, 0, 0),
                    ),
                    4,
                ),
                TStreamerBasicType(_el("fNbins", "int", 3, 4, "Number of bins")),
                TStreamerBasicType(_el("fXmin", "double", 8, 8, "Low edge of first bin")),
                TStreamerBasicType(_el("fXmax", "double", 8, 8, "Upper edge of last bin")),
                TStreamerObjectAny(
                    _el("fXbins", "TArrayD", 62, 24, "Bin edges array in X")
                ),
                TStreamerBasicType(_el("fFirst", "int", 3, 4, "First bin to display")),
                TStreamerBasicType(_el("fLast", "int", 3, 4, "Last bin to display")),
                TStreamerBasicType(
                    _el("fBits2", "unsigned short", 12, 2, "Second bit status word")
                ),
                TStreamerBasicType(
                    _el(
                        "fTimeDisplay",
                        "bool",
                        18,
                        1,
                        "On/off displaying time values instead of numerics",
                    ),
                ),
                TStreamerString(
                    _el(
                        "fTimeFormat",
                        "TString",
                        65,
                        24,
                        "Date&time format, ex: 09/12/99 12:34:00",
                    ),
                ),
                TStreamerObjectPointer(
                    _el("fLabels", "THashList*", 64, 8, "List of labels")
                ),
                TStreamerObjectPointer(
                    _el("fModLabs", "TList*", 64, 8, "List of modified labels")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TBranch",
            13;
            checksum=0x10978aac,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBase(
                    _el(
                        "TAttFill",
                        "BASE",
                        0,
                        0,
                        "Fill area attributes";
                        maxidx=(0, -2545006, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el("fCompress", "int", 3, 4, "Compression level and algorithm")
                ),
                TStreamerBasicType(
                    _el("fBasketSize", "int", 3, 4, "Initial Size of  Basket Buffer")
                ),
                TStreamerBasicType(
                    _el(
                        "fEntryOffsetLen",
                        "int",
                        3,
                        4,
                        "Initial Length of fEntryOffset table in the basket buffers",
                    ),
                ),
                TStreamerBasicType(
                    _el("fWriteBasket", "int", 3, 4, "Last basket number written")
                ),
                TStreamerBasicType(
                    _el(
                        "fEntryNumber",
                        "Long64_t",
                        16,
                        8,
                        "Current entry number (last one filled in this branch)",
                    ),
                ),
                TStreamerObjectAny(
                    _el(
                        "fIOFeatures",
                        "ROOT::TIOFeatures",
                        62,
                        1,
                        "IO features for newly-created baskets.",
                    ),
                ),
                TStreamerBasicType(_el("fOffset", "int", 3, 4, "Offset of this branch")),
                TStreamerBasicType(
                    _el("fMaxBaskets", "int", 6, 4, "Maximum number of Baskets so far")
                ),
                TStreamerBasicType(_el("fSplitLevel", "int", 3, 4, "Branch split level")),
                TStreamerBasicType(_el("fEntries", "Long64_t", 16, 8, "Number of entries")),
                TStreamerBasicType(
                    _el(
                        "fFirstEntry",
                        "Long64_t",
                        16,
                        8,
                        "Number of the first entry in this branch",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fTotBytes",
                        "Long64_t",
                        16,
                        8,
                        "Total number of bytes in all leaves before compression",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fZipBytes",
                        "Long64_t",
                        16,
                        8,
                        "Total number of bytes in all leaves after compression",
                    ),
                ),
                TStreamerObject(
                    _el(
                        "fBranches",
                        "TObjArray",
                        61,
                        64,
                        "-> List of Branches of this branch",
                    ),
                ),
                TStreamerObject(
                    _el("fLeaves", "TObjArray", 61, 64, "-> List of leaves of this branch")
                ),
                TStreamerObject(
                    _el(
                        "fBaskets", "TObjArray", 61, 64, "-> List of baskets of this branch"
                    ),
                ),
                TStreamerBasicPointer(
                    _el(
                        "fBasketBytes",
                        "int*",
                        43,
                        4,
                        "[fMaxBaskets] Length of baskets on file",
                    ),
                    13,
                    "fMaxBaskets",
                    "TBranch",
                ),
                TStreamerBasicPointer(
                    _el(
                        "fBasketEntry",
                        "Long64_t*",
                        56,
                        8,
                        "[fMaxBaskets] Table of first entry in each basket",
                    ),
                    13,
                    "fMaxBaskets",
                    "TBranch",
                ),
                TStreamerBasicPointer(
                    _el(
                        "fBasketSeek",
                        "Long64_t*",
                        56,
                        8,
                        "[fMaxBaskets] Addresses of baskets on file",
                    ),
                    13,
                    "fMaxBaskets",
                    "TBranch",
                ),
                TStreamerString(
                    _el(
                        "fFileName",
                        "TString",
                        65,
                        24,
                        "Name of file where buffers are stored (\"\" if in same file as Tree header)",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TBranchElement",
            10;
            checksum=0xe74f5e63,
            elems=[
                TStreamerBase(
                    _el(
                        "TBranch",
                        "BASE",
                        0,
                        0,
                        "Branch descriptor";
                        maxidx=(0, 278366892, 0, 0, 0),
                    ),
                    13,
                ),
                TStreamerString(
                    _el("fClassName", "TString", 65, 24, "Class name of referenced object")
                ),
                TStreamerString(
                    _el("fParentName", "TString", 65, 24, "Name of parent class")
                ),
                TStreamerString(
                    _el(
                        "fClonesName",
                        "TString",
                        65,
                        24,
                        "Name of class in TClonesArray or (STL) collection (if any)",
                    ),
                ),
                TStreamerBasicType(
                    _el("fCheckSum", "unsigned int", 13, 4, "CheckSum of class")
                ),
                TStreamerBasicType(
                    _el("fClassVersion", "short", 2, 2, "Version number of class")
                ),
                TStreamerBasicType(
                    _el("fID", "int", 3, 4, "element serial number in fInfo")
                ),
                TStreamerBasicType(_el("fType", "int", 3, 4, "Branch type")),
                TStreamerBasicType(
                    _el("fStreamerType", "int", 3, 4, "branch streamer type")
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "int",
                        3,
                        4,
                        "Maximum entries for a TClonesArray or variable array",
                    ),
                ),
                TStreamerObjectPointer(
                    _el(
                        "fBranchCount",
                        "TBranchElement*",
                        64,
                        8,
                        "pointer to primary branchcount branch",
                    ),
                ),
                TStreamerObjectPointer(
                    _el(
                        "fBranchCount2",
                        "TBranchElement*",
                        64,
                        8,
                        "pointer to secondary branchcount branch",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TBranchObject",
            1;
            checksum=0xa4720f49,
            elems=[
                TStreamerBase(
                    _el(
                        "TBranch",
                        "BASE",
                        0,
                        0,
                        "Branch descriptor";
                        maxidx=(0, 278366892, 0, 0, 0),
                    ),
                    13,
                ),
                TStreamerString(
                    _el("fClassName", "TString", 65, 24, "Class name of referenced object")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TBranchRef",
            1;
            checksum=0x2360b3fd,
            elems=[
                TStreamerBase(
                    _el(
                        "TBranch",
                        "BASE",
                        0,
                        0,
                        "Branch descriptor";
                        maxidx=(0, 278366892, 0, 0, 0),
                    ),
                    13,
                ),
                TStreamerObjectPointer(
                    _el("fRefTable", "TRefTable*", 64, 8, "pointer to the TRefTable")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TCollection",
            3;
            checksum=0x57e3cb9c,
            elems=[
                TStreamerBase(
                    _el(
                        "TObject",
                        "BASE",
                        66,
                        0,
                        "Basic ROOT object";
                        maxidx=(0, -1877229523, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerString(_el("fName", "TString", 65, 24, "name of the collection")),
                TStreamerBasicType(
                    _el("fSize", "int", 3, 4, "number of elements in collection")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TGraph",
            5;
            checksum=0xb932984f,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBase(
                    _el(
                        "TAttLine",
                        "BASE",
                        0,
                        0,
                        "Line attributes";
                        maxidx=(0, -1811462839, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBase(
                    _el(
                        "TAttFill",
                        "BASE",
                        0,
                        0,
                        "Fill area attributes";
                        maxidx=(0, -2545006, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBase(
                    _el(
                        "TAttMarker",
                        "BASE",
                        0,
                        0,
                        "Marker attributes";
                        maxidx=(0, 689802220, 0, 0, 0),
                    ),
                    3,
                ),
                TStreamerBasicType(
                    _el("fNpoints", "int", 6, 4, "Number of points <= fMaxSize")
                ),
                TStreamerBasicPointer(
                    _el("fX", "double*", 48, 8, "[fNpoints] array of X points"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
                TStreamerBasicPointer(
                    _el("fY", "double*", 48, 8, "[fNpoints] array of Y points"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
                TStreamerObjectPointer(
                    _el(
                        "fFunctions",
                        "TList*",
                        64,
                        8,
                        "Pointer to list of functions (fits and user)",
                    ),
                ),
                TStreamerObjectPointer(
                    _el(
                        "fHistogram",
                        "TH1F*",
                        64,
                        8,
                        "Pointer to histogram used for drawing axis",
                    ),
                ),
                TStreamerBasicType(
                    _el("fMinimum", "double", 8, 8, "Minimum value for plotting along y")
                ),
                TStreamerBasicType(
                    _el("fMaximum", "double", 8, 8, "Maximum value for plotting along y")
                ),
                TStreamerString(
                    _el("fOption", "TString", 65, 24, "Options used for drawing the graph")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TGraphAsymmErrors",
            3;
            checksum=0x206d5315,
            elems=[
                TStreamerBase(
                    _el(
                        "TGraph",
                        "BASE",
                        0,
                        0,
                        "Graph graphics class";
                        maxidx=(0, -1187866545, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBasicPointer(
                    _el("fEXlow", "double*", 48, 8, "[fNpoints] array of X low errors"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
                TStreamerBasicPointer(
                    _el("fEXhigh", "double*", 48, 8, "[fNpoints] array of X high errors"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
                TStreamerBasicPointer(
                    _el("fEYlow", "double*", 48, 8, "[fNpoints] array of Y low errors"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
                TStreamerBasicPointer(
                    _el("fEYhigh", "double*", 48, 8, "[fNpoints] array of Y high errors"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TGraphErrors",
            3;
            checksum=0xbdadb119,
            elems=[
                TStreamerBase(
                    _el(
                        "TGraph",
                        "BASE",
                        0,
                        0,
                        "Graph graphics class";
                        maxidx=(0, -1187866545, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBasicPointer(
                    _el("fEX", "double*", 48, 8, "[fNpoints] array of X errors"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
                TStreamerBasicPointer(
                    _el("fEY", "double*", 48, 8, "[fNpoints] array of Y errors"),
                    5,
                    "fNpoints",
                    "TGraph",
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH1",
            8;
            checksum=0x1c3740c4,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBase(
                    _el(
                        "TAttLine",
                        "BASE",
                        0,
                        0,
                        "Line attributes";
                        maxidx=(0, -1811462839, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBase(
                    _el(
                        "TAttFill",
                        "BASE",
                        0,
                        0,
                        "Fill area attributes";
                        maxidx=(0, -2545006, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBase(
                    _el(
                        "TAttMarker",
                        "BASE",
                        0,
                        0,
                        "Marker attributes";
                        maxidx=(0, 689802220, 0, 0, 0),
                    ),
                    3,
                ),
                TStreamerBasicType(
                    _el(
                        "fNcells",
                        "int",
                        3,
                        4,
                        "Number of bins(1D), cells (2D) +U/Overflows",
                    ),
                ),
                TStreamerObject(_el("fXaxis", "TAxis", 61, 216, "X axis descriptor")),
                TStreamerObject(_el("fYaxis", "TAxis", 61, 216, "Y axis descriptor")),
                TStreamerObject(_el("fZaxis", "TAxis", 61, 216, "Z axis descriptor")),
                TStreamerBasicType(
                    _el(
                        "fBarOffset", "short", 2, 2, "(1000*offset) for bar charts or legos"
                    ),
                ),
                TStreamerBasicType(
                    _el("fBarWidth", "short", 2, 2, "(1000*width) for bar charts or legos")
                ),
                TStreamerBasicType(_el("fEntries", "double", 8, 8, "Number of entries")),
                TStreamerBasicType(_el("fTsumw", "double", 8, 8, "Total Sum of weights")),
                TStreamerBasicType(
                    _el("fTsumw2", "double", 8, 8, "Total Sum of squares of weights")
                ),
                TStreamerBasicType(_el("fTsumwx", "double", 8, 8, "Total Sum of weight*X")),
                TStreamerBasicType(
                    _el("fTsumwx2", "double", 8, 8, "Total Sum of weight*X*X")
                ),
                TStreamerBasicType(
                    _el("fMaximum", "double", 8, 8, "Maximum value for plotting")
                ),
                TStreamerBasicType(
                    _el("fMinimum", "double", 8, 8, "Minimum value for plotting")
                ),
                TStreamerBasicType(
                    _el("fNormFactor", "double", 8, 8, "Normalization factor")
                ),
                TStreamerObjectAny(
                    _el("fContour", "TArrayD", 62, 24, "Array to display contour levels")
                ),
                TStreamerObjectAny(
                    _el("fSumw2", "TArrayD", 62, 24, "Array of sum of squares of weights")
                ),
                TStreamerString(_el("fOption", "TString", 65, 24, "Histogram options")),
                TStreamerObjectPointer(
                    _el(
                        "fFunctions",
                        "TList*",
                        63,
                        8,
                        "->Pointer to list of functions (fits and user)",
                    ),
                ),
                TStreamerBasicType(_el("fBufferSize", "int", 6, 4, "fBuffer size")),
                TStreamerBasicPointer(
                    _el("fBuffer", "double*", 48, 8, "[fBufferSize] entry buffer"),
                    8,
                    "fBufferSize",
                    "TH1",
                ),
                TStreamerBasicType(
                    _el(
                        "fBinStatErrOpt",
                        "TH1::EBinErrorOpt",
                        3,
                        4,
                        "Option for bin statistical errors",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fStatOverflows",
                        "TH1::EStatOverflows",
                        3,
                        4,
                        "Per object flag to use under/overflows in statistics",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH1C",
            3;
            checksum=0x36f6e4ad,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBase(
                    _el(
                        "TArrayC",
                        "BASE",
                        0,
                        0,
                        "Array of chars";
                        maxidx=(0, -1366845130, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH1D",
            3;
            checksum=0xf9b1569f,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBase(
                    _el(
                        "TArrayD",
                        "BASE",
                        0,
                        0,
                        "Array of doubles";
                        maxidx=(0, 1899622196, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH1F",
            3;
            checksum=0xe2939644,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBase(
                    _el(
                        "TArrayF",
                        "BASE",
                        0,
                        0,
                        "Array of floats";
                        maxidx=(0, 1510733553, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH1I",
            3;
            checksum=0x627564f6,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBase(
                    _el(
                        "TArrayI",
                        "BASE",
                        0,
                        0,
                        "Array of ints";
                        maxidx=(0, -640323129, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH1L",
            0;
            checksum=0xe7618979,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBase(
                    _el(
                        "TArrayL64",
                        "BASE",
                        0,
                        0,
                        "Array of long64s";
                        maxidx=(0, 417793940, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH1S",
            3;
            checksum=0x8c4d9dcb,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBase(
                    _el(
                        "TArrayS",
                        "BASE",
                        0,
                        0,
                        "Array of shorts";
                        maxidx=(0, 56398612, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH2",
            5;
            checksum=0x0182347f,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBasicType(_el("fScalefactor", "double", 8, 8, "Scale factor")),
                TStreamerBasicType(_el("fTsumwy", "double", 8, 8, "Total Sum of weight*Y")),
                TStreamerBasicType(
                    _el("fTsumwy2", "double", 8, 8, "Total Sum of weight*Y*Y")
                ),
                TStreamerBasicType(
                    _el("fTsumwxy", "double", 8, 8, "Total Sum of weight*X*Y")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH2C",
            4;
            checksum=0xbd0010fe,
            elems=[
                TStreamerBase(
                    _el(
                        "TH2",
                        "BASE",
                        0,
                        0,
                        "2-Dim histogram base class";
                        maxidx=(0, 25310335, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBase(
                    _el(
                        "TArrayC",
                        "BASE",
                        0,
                        0,
                        "Array of chars";
                        maxidx=(0, -1366845130, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH2D",
            4;
            checksum=0x7fba82f0,
            elems=[
                TStreamerBase(
                    _el(
                        "TH2",
                        "BASE",
                        0,
                        0,
                        "2-Dim histogram base class";
                        maxidx=(0, 25310335, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBase(
                    _el(
                        "TArrayD",
                        "BASE",
                        0,
                        0,
                        "Array of doubles";
                        maxidx=(0, 1899622196, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH2F",
            4;
            checksum=0x689cc295,
            elems=[
                TStreamerBase(
                    _el(
                        "TH2",
                        "BASE",
                        0,
                        0,
                        "2-Dim histogram base class";
                        maxidx=(0, 25310335, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBase(
                    _el(
                        "TArrayF",
                        "BASE",
                        0,
                        0,
                        "Array of floats";
                        maxidx=(0, 1510733553, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH2I",
            4;
            checksum=0xe87e9147,
            elems=[
                TStreamerBase(
                    _el(
                        "TH2",
                        "BASE",
                        0,
                        0,
                        "2-Dim histogram base class";
                        maxidx=(0, 25310335, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBase(
                    _el(
                        "TArrayI",
                        "BASE",
                        0,
                        0,
                        "Array of ints";
                        maxidx=(0, -640323129, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH2L",
            0;
            checksum=0x9db41852,
            elems=[
                TStreamerBase(
                    _el(
                        "TH2",
                        "BASE",
                        0,
                        0,
                        "2-Dim histogram base class";
                        maxidx=(0, 25310335, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBase(
                    _el(
                        "TArrayL64",
                        "BASE",
                        0,
                        0,
                        "Array of long64s";
                        maxidx=(0, 417793940, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH2S",
            4;
            checksum=0x1256ca1c,
            elems=[
                TStreamerBase(
                    _el(
                        "TH2",
                        "BASE",
                        0,
                        0,
                        "2-Dim histogram base class";
                        maxidx=(0, 25310335, 0, 0, 0),
                    ),
                    5,
                ),
                TStreamerBase(
                    _el(
                        "TArrayS",
                        "BASE",
                        0,
                        0,
                        "Array of shorts";
                        maxidx=(0, 56398612, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH3",
            6;
            checksum=0x42d2445f,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1",
                        "BASE",
                        0,
                        0,
                        "1-Dim histogram base class";
                        maxidx=(0, 473383108, 0, 0, 0),
                    ),
                    8,
                ),
                TStreamerBase(
                    _el(
                        "TAtt3D", "BASE", 0, 0, "3D attributes"; maxidx=(0, 30074, 0, 0, 0)
                    ),
                    1,
                ),
                TStreamerBasicType(_el("fTsumwy", "double", 8, 8, "Total Sum of weight*Y")),
                TStreamerBasicType(
                    _el("fTsumwy2", "double", 8, 8, "Total Sum of weight*Y*Y")
                ),
                TStreamerBasicType(
                    _el("fTsumwxy", "double", 8, 8, "Total Sum of weight*X*Y")
                ),
                TStreamerBasicType(_el("fTsumwz", "double", 8, 8, "Total Sum of weight*Z")),
                TStreamerBasicType(
                    _el("fTsumwz2", "double", 8, 8, "Total Sum of weight*Z*Z")
                ),
                TStreamerBasicType(
                    _el("fTsumwxz", "double", 8, 8, "Total Sum of weight*X*Z")
                ),
                TStreamerBasicType(
                    _el("fTsumwyz", "double", 8, 8, "Total Sum of weight*Y*Z")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH3C",
            4;
            checksum=0xa1ff8d94,
            elems=[
                TStreamerBase(
                    _el(
                        "TH3",
                        "BASE",
                        0,
                        0,
                        "3-Dim histogram base class";
                        maxidx=(0, 1121076319, 0, 0, 0),
                    ),
                    6,
                ),
                TStreamerBase(
                    _el(
                        "TArrayC",
                        "BASE",
                        0,
                        0,
                        "Array of chars";
                        maxidx=(0, -1366845130, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH3D",
            4;
            checksum=0x64b9ff86,
            elems=[
                TStreamerBase(
                    _el(
                        "TH3",
                        "BASE",
                        0,
                        0,
                        "3-Dim histogram base class";
                        maxidx=(0, 1121076319, 0, 0, 0),
                    ),
                    6,
                ),
                TStreamerBase(
                    _el(
                        "TArrayD",
                        "BASE",
                        0,
                        0,
                        "Array of doubles";
                        maxidx=(0, 1899622196, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH3F",
            4;
            checksum=0x4d9c3f2b,
            elems=[
                TStreamerBase(
                    _el(
                        "TH3",
                        "BASE",
                        0,
                        0,
                        "3-Dim histogram base class";
                        maxidx=(0, 1121076319, 0, 0, 0),
                    ),
                    6,
                ),
                TStreamerBase(
                    _el(
                        "TArrayF",
                        "BASE",
                        0,
                        0,
                        "Array of floats";
                        maxidx=(0, 1510733553, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH3I",
            4;
            checksum=0xcd7e0ddd,
            elems=[
                TStreamerBase(
                    _el(
                        "TH3",
                        "BASE",
                        0,
                        0,
                        "3-Dim histogram base class";
                        maxidx=(0, 1121076319, 0, 0, 0),
                    ),
                    6,
                ),
                TStreamerBase(
                    _el(
                        "TArrayI",
                        "BASE",
                        0,
                        0,
                        "Array of ints";
                        maxidx=(0, -640323129, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH3L",
            0;
            checksum=0xaaaf7998,
            elems=[
                TStreamerBase(
                    _el(
                        "TH3",
                        "BASE",
                        0,
                        0,
                        "3-Dim histogram base class";
                        maxidx=(0, 1121076319, 0, 0, 0),
                    ),
                    6,
                ),
                TStreamerBase(
                    _el(
                        "TArrayL64",
                        "BASE",
                        0,
                        0,
                        "Array of long64s";
                        maxidx=(0, 417793940, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TH3S",
            4;
            checksum=0xf75646b2,
            elems=[
                TStreamerBase(
                    _el(
                        "TH3",
                        "BASE",
                        0,
                        0,
                        "3-Dim histogram base class";
                        maxidx=(0, 1121076319, 0, 0, 0),
                    ),
                    6,
                ),
                TStreamerBase(
                    _el(
                        "TArrayS",
                        "BASE",
                        0,
                        0,
                        "Array of shorts";
                        maxidx=(0, 56398612, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "THashList",
            0;
            checksum=0xcc7e49c1,
            elems=[
                TStreamerBase(
                    _el(
                        "TList",
                        "BASE",
                        0,
                        0,
                        "Doubly linked list";
                        maxidx=(0, 1774568379, 0, 0, 0),
                    ),
                    5,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeaf",
            2;
            checksum=0x6d1e8152,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicType(
                    _el(
                        "fLen",
                        "int",
                        3,
                        4,
                        "Number of fixed length elements in the leaf's data.",
                    ),
                ),
                TStreamerBasicType(
                    _el("fLenType", "int", 3, 4, "Number of bytes for this data type")
                ),
                TStreamerBasicType(
                    _el("fOffset", "int", 3, 4, "Offset in ClonesArray object (if one)")
                ),
                TStreamerBasicType(
                    _el(
                        "fIsRange",
                        "bool",
                        18,
                        1,
                        "(=true if leaf has a range, false otherwise).  This is equivalent to being a 'leafcount'.  For a TLeafElement the range information is actually store in the TBranchElement.",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fIsUnsigned", "bool", 18, 1, "(=true if unsigned, false otherwise)"
                    ),
                ),
                TStreamerObjectPointer(
                    _el(
                        "fLeafCount",
                        "TLeaf*",
                        64,
                        8,
                        "Pointer to Leaf count if variable length (we do not own the counter)",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafB",
            1;
            checksum=0x0f1e4b5e,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum", "char", 1, 1, "Minimum value if leaf range is specified"
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum", "char", 1, 1, "Maximum value if leaf range is specified"
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafC",
            1;
            checksum=0xfbe3b2f3,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el("fMinimum", "int", 3, 4, "Minimum value if leaf range is specified")
                ),
                TStreamerBasicType(
                    _el("fMaximum", "int", 3, 4, "Maximum value if leaf range is specified")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafD",
            1;
            checksum=0x118e8776,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum",
                        "double",
                        8,
                        8,
                        "Minimum value if leaf range is specified",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "double",
                        8,
                        8,
                        "Maximum value if leaf range is specified",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafD32",
            2;
            checksum=0xe1dc6401,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum",
                        "Double32_t",
                        9,
                        8,
                        "Minimum value if leaf range is specified",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "Double32_t",
                        9,
                        8,
                        "Maximum value if leaf range is specified",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafElement",
            1;
            checksum=0xa04f8893,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el("fID", "int", 3, 4, "element serial number in fInfo")
                ),
                TStreamerBasicType(_el("fType", "int", 3, 4, "leaf type")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafF",
            1;
            checksum=0x3add9d72,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum",
                        "float",
                        5,
                        4,
                        "Minimum value if leaf range is specified",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "float",
                        5,
                        4,
                        "Maximum value if leaf range is specified",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafF16",
            2;
            checksum=0xeb35f883,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum",
                        "Float16_t",
                        19,
                        4,
                        "Minimum value if leaf range is specified",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "Float16_t",
                        19,
                        4,
                        "Maximum value if leaf range is specified",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafG",
            1;
            checksum=0xeca71cb7,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum", "long", 4, 8, "Minimum value if leaf range is specified"
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum", "long", 4, 8, "Maximum value if leaf range is specified"
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafI",
            1;
            checksum=0x7e6aae19,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el("fMinimum", "int", 3, 4, "Minimum value if leaf range is specified")
                ),
                TStreamerBasicType(
                    _el("fMaximum", "int", 3, 4, "Maximum value if leaf range is specified")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafL",
            1;
            checksum=0xde320862,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum",
                        "Long64_t",
                        16,
                        8,
                        "Minimum value if leaf range is specified",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "Long64_t",
                        16,
                        8,
                        "Maximum value if leaf range is specified",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafO",
            1;
            checksum=0x02ae48d3,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum",
                        "bool",
                        18,
                        1,
                        "Minimum value if leaf range is specified",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "bool",
                        18,
                        1,
                        "Maximum value if leaf range is specified",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafObject",
            4;
            checksum=0x26ba7c4c,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fVirtual",
                        "bool",
                        18,
                        1,
                        "Support for polymorphism, when set classname is written with object.",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TLeafS",
            1;
            checksum=0x150ceecf,
            elems=[
                TStreamerBase(
                    _el(
                        "TLeaf",
                        "BASE",
                        0,
                        0,
                        "Leaf: description of a Branch data type";
                        maxidx=(0, 1830715730, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBasicType(
                    _el(
                        "fMinimum",
                        "short",
                        2,
                        2,
                        "Minimum value if leaf range is specified",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaximum",
                        "short",
                        2,
                        2,
                        "Maximum value if leaf range is specified",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TList",
            5;
            checksum=0x69c5c3bb,
            elems=[
                TStreamerBase(
                    _el(
                        "TSeqCollection",
                        "BASE",
                        0,
                        0,
                        "Sequenceable collection ABC";
                        maxidx=(0, -60015674, 0, 0, 0),
                    ),
                    0,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TNamed",
            1;
            checksum=0xdfb74a3c,
            elems=[
                TStreamerBase(
                    _el(
                        "TObject",
                        "BASE",
                        66,
                        0,
                        "Basic ROOT object";
                        maxidx=(0, -1877229523, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerString(_el("fName", "TString", 65, 24, "object identifier")),
                TStreamerString(_el("fTitle", "TString", 65, 24, "object title")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TNtuple",
            2;
            checksum=0xb8a51cab,
            elems=[
                TStreamerBase(
                    _el(
                        "TTree",
                        "BASE",
                        0,
                        0,
                        "Tree descriptor (the main ROOT I/O class)";
                        maxidx=(0, 1919213695, 0, 0, 0),
                    ),
                    20,
                ),
                TStreamerBasicType(_el("fNvar", "int", 3, 4, "Number of columns")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TNtupleD",
            1;
            checksum=0x8de8d873,
            elems=[
                TStreamerBase(
                    _el(
                        "TTree",
                        "BASE",
                        0,
                        0,
                        "Tree descriptor (the main ROOT I/O class)";
                        maxidx=(0, 1919213695, 0, 0, 0),
                    ),
                    20,
                ),
                TStreamerBasicType(_el("fNvar", "int", 3, 4, "Number of columns")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TObjArray",
            3;
            checksum=0xa99e6552,
            elems=[
                TStreamerBase(
                    _el(
                        "TSeqCollection",
                        "BASE",
                        0,
                        0,
                        "Sequenceable collection ABC";
                        maxidx=(0, -60015674, 0, 0, 0),
                    ),
                    0,
                ),
                TStreamerBasicType(
                    _el("fLowerBound", "int", 3, 4, "Lower bound of the array")
                ),
                TStreamerBasicType(
                    _el("fLast", "int", 3, 4, "Last element in array containing an object")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TObjString",
            1;
            checksum=0x9c8e4800,
            elems=[
                TStreamerBase(
                    _el(
                        "TObject",
                        "BASE",
                        66,
                        0,
                        "Basic ROOT object";
                        maxidx=(0, -1877229523, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerString(_el("fString", "TString", 65, 24, "wrapped TString")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TObject",
            1;
            checksum=0x901bc02d,
            elems=[
                TStreamerBasicType(
                    _el("fUniqueID", "unsigned int", 13, 4, "object unique identifier")
                ),
                TStreamerBasicType(
                    _el("fBits", "unsigned int", 15, 4, "bit field status word")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TProfile",
            7;
            checksum=0x4bedee54,
            elems=[
                TStreamerBase(
                    _el(
                        "TH1D",
                        "BASE",
                        0,
                        0,
                        "1-Dim histograms (one double per channel)";
                        maxidx=(0, -105818465, 0, 0, 0),
                    ),
                    3,
                ),
                TStreamerObjectAny(
                    _el("fBinEntries", "TArrayD", 62, 24, "number of entries per bin")
                ),
                TStreamerBasicType(
                    _el("fErrorMode", "EErrorType", 3, 4, "Option to compute errors")
                ),
                TStreamerBasicType(
                    _el("fYmin", "double", 8, 8, "Lower limit in Y (if set)")
                ),
                TStreamerBasicType(
                    _el("fYmax", "double", 8, 8, "Upper limit in Y (if set)")
                ),
                TStreamerBasicType(_el("fTsumwy", "double", 8, 8, "Total Sum of weight*Y")),
                TStreamerBasicType(
                    _el("fTsumwy2", "double", 8, 8, "Total Sum of weight*Y*Y")
                ),
                TStreamerObjectAny(
                    _el(
                        "fBinSumw2",
                        "TArrayD",
                        62,
                        24,
                        "Array of sum of squares of weights per bin",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TProfile2D",
            8;
            checksum=0x36a142ac,
            elems=[
                TStreamerBase(
                    _el(
                        "TH2D",
                        "BASE",
                        0,
                        0,
                        "2-Dim histograms (one double per channel)";
                        maxidx=(0, 2142929648, 0, 0, 0),
                    ),
                    4,
                ),
                TStreamerObjectAny(
                    _el("fBinEntries", "TArrayD", 62, 24, "Number of entries per bin")
                ),
                TStreamerBasicType(
                    _el("fErrorMode", "EErrorType", 3, 4, "Option to compute errors")
                ),
                TStreamerBasicType(
                    _el("fZmin", "double", 8, 8, "Lower limit in Z (if set)")
                ),
                TStreamerBasicType(
                    _el("fZmax", "double", 8, 8, "Upper limit in Z (if set)")
                ),
                TStreamerBasicType(_el("fTsumwz", "double", 8, 8, "Total Sum of weight*Z")),
                TStreamerBasicType(
                    _el("fTsumwz2", "double", 8, 8, "Total Sum of weight*Z*Z")
                ),
                TStreamerObjectAny(
                    _el(
                        "fBinSumw2",
                        "TArrayD",
                        62,
                        24,
                        "Array of sum of squares of weights per bin",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TRefTable",
            3;
            checksum=0x8c895b85,
            elems=[
                TStreamerBase(
                    _el(
                        "TObject",
                        "BASE",
                        66,
                        0,
                        "Basic ROOT object";
                        maxidx=(0, -1877229523, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicType(
                    _el("fSize", "int", 3, 4, "dummy for backward compatibility")
                ),
                TStreamerObjectPointer(
                    _el(
                        "fParents",
                        "TObjArray*",
                        64,
                        8,
                        "array of Parent objects  (eg TTree branch) holding the referenced objects",
                    ),
                ),
                TStreamerObjectPointer(
                    _el("fOwner", "TObject*", 64, 8, "Object owning this TRefTable")
                ),
                TStreamerSTL(
                    _el(
                        "fProcessGUIDs",
                        "vector<string>",
                        500,
                        24,
                        "UUIDs of TProcessIDs used in fParentIDs",
                    ),
                    1,
                    61,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TSeqCollection",
            0;
            checksum=0xfc6c3bc6,
            elems=[
                TStreamerBase(
                    _el(
                        "TCollection",
                        "BASE",
                        0,
                        0,
                        "Collection abstract base class";
                        maxidx=(0, 1474546588, 0, 0, 0),
                    ),
                    3,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerArtificial",
            0;
            checksum=0x5629bbc9,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerBase",
            3;
            checksum=0x092715b0,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
                TStreamerBasicType(
                    _el(
                        "fBaseVersion",
                        "int",
                        3,
                        4,
                        "version number of the base class (used during memberwise streaming)",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerBasicPointer",
            2;
            checksum=0x0318803b,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
                TStreamerBasicType(
                    _el(
                        "fCountVersion",
                        "int",
                        3,
                        4,
                        "version number of the class with the counter",
                    ),
                ),
                TStreamerString(
                    _el(
                        "fCountName",
                        "TString",
                        65,
                        24,
                        "name of data member holding the array count",
                    ),
                ),
                TStreamerString(
                    _el(
                        "fCountClass",
                        "TString",
                        65,
                        24,
                        "name of the class with the counter",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerBasicType",
            2;
            checksum=0xf5d5ac4d,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerElement",
            4;
            checksum=0xdd0eb253,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBasicType(_el("fType", "int", 3, 4, "element type")),
                TStreamerBasicType(_el("fSize", "int", 3, 4, "sizeof element")),
                TStreamerBasicType(
                    _el("fArrayLength", "int", 3, 4, "cumulative size of all array dims")
                ),
                TStreamerBasicType(
                    _el("fArrayDim", "int", 3, 4, "number of array dimensions")
                ),
                TStreamerBasicType(
                    _el(
                        "fMaxIndex",
                        "int",
                        23,
                        20,
                        "Maximum array index for array dimension \"dim\"";
                        arrlen=5,
                        arrdim=1,
                        maxidx=(5, 0, 0, 0, 0),
                    ),
                ),
                TStreamerString(
                    _el("fTypeName", "TString", 65, 24, "Data type name of data member")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerInfo",
            10;
            checksum=0x90566883,
            elems=[
                TStreamerBase(
                    _el(
                        "TVirtualStreamerInfo",
                        "BASE",
                        0,
                        0,
                        "Abstract Interface describing Streamer information for one class";
                        maxidx=(0, 1154605729, 0, 0, 0),
                    ),
                    6,
                ),
                TStreamerBasicType(
                    _el("fCheckSum", "unsigned int", 13, 4, "Checksum of original class")
                ),
                TStreamerBasicType(
                    _el("fClassVersion", "int", 3, 4, "Class version identifier")
                ),
                TStreamerObjectPointer(
                    _el("fElements", "TObjArray*", 64, 8, "Array of TStreamerElements")
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerLoop",
            2;
            checksum=0xf350b8dc,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
                TStreamerBasicType(
                    _el(
                        "fCountVersion",
                        "int",
                        3,
                        4,
                        "version number of the class with the counter",
                    ),
                ),
                TStreamerString(
                    _el(
                        "fCountName",
                        "TString",
                        65,
                        24,
                        "name of data member holding the array count",
                    ),
                ),
                TStreamerString(
                    _el(
                        "fCountClass",
                        "TString",
                        65,
                        24,
                        "name of the class with the counter",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerObject",
            2;
            checksum=0x626ac134,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerObjectAny",
            2;
            checksum=0x08f7ef50,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerObjectAnyPointer",
            1;
            checksum=0x3600167f,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerObjectPointer",
            2;
            checksum=0x5de72d4b,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerSTL",
            3;
            checksum=0x89f908d6,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
                TStreamerBasicType(_el("fSTLtype", "int", 3, 4, "type of STL vector")),
                TStreamerBasicType(_el("fCtype", "int", 3, 4, "STL contained type")),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerSTLstring",
            2;
            checksum=0x262eefa1,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerSTL",
                        "BASE",
                        0,
                        0,
                        "Streamer element of type STL container";
                        maxidx=(0, -1980167978, 0, 0, 0),
                    ),
                    3,
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TStreamerString",
            2;
            checksum=0xa0aa915e,
            elems=[
                TStreamerBase(
                    _el(
                        "TStreamerElement",
                        "BASE",
                        0,
                        0,
                        "Base class for one element (data member) to be Streamed";
                        maxidx=(0, -586239405, 0, 0, 0),
                    ),
                    4,
                ),
            ],
        ),
    )

    push!(v, TStreamerInfo("TString", 2; checksum=0x00017419, elems=[]))

    push!(
        v,
        TStreamerInfo(
            "TTree",
            20;
            checksum=0x7264e07f,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
                TStreamerBase(
                    _el(
                        "TAttLine",
                        "BASE",
                        0,
                        0,
                        "Line attributes";
                        maxidx=(0, -1811462839, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBase(
                    _el(
                        "TAttFill",
                        "BASE",
                        0,
                        0,
                        "Fill area attributes";
                        maxidx=(0, -2545006, 0, 0, 0),
                    ),
                    2,
                ),
                TStreamerBase(
                    _el(
                        "TAttMarker",
                        "BASE",
                        0,
                        0,
                        "Marker attributes";
                        maxidx=(0, 689802220, 0, 0, 0),
                    ),
                    3,
                ),
                TStreamerBasicType(_el("fEntries", "Long64_t", 16, 8, "Number of entries")),
                TStreamerBasicType(
                    _el(
                        "fTotBytes",
                        "Long64_t",
                        16,
                        8,
                        "Total number of bytes in all branches before compression",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fZipBytes",
                        "Long64_t",
                        16,
                        8,
                        "Total number of bytes in all branches after compression",
                    ),
                ),
                TStreamerBasicType(
                    _el("fSavedBytes", "Long64_t", 16, 8, "Number of autosaved bytes")
                ),
                TStreamerBasicType(
                    _el("fFlushedBytes", "Long64_t", 16, 8, "Number of auto-flushed bytes")
                ),
                TStreamerBasicType(
                    _el("fWeight", "double", 8, 8, "Tree weight (see TTree::SetWeight)")
                ),
                TStreamerBasicType(
                    _el("fTimerInterval", "int", 3, 4, "Timer interval in milliseconds")
                ),
                TStreamerBasicType(
                    _el(
                        "fScanField", "int", 3, 4, "Number of runs before prompting in Scan"
                    ),
                ),
                TStreamerBasicType(
                    _el("fUpdate", "int", 3, 4, "Update frequency for EntryLoop")
                ),
                TStreamerBasicType(
                    _el(
                        "fDefaultEntryOffsetLen",
                        "int",
                        3,
                        4,
                        "Initial Length of fEntryOffset table in the basket buffers",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fNClusterRange",
                        "int",
                        6,
                        4,
                        "Number of Cluster range in addition to the one defined by 'AutoFlush'",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaxEntries",
                        "Long64_t",
                        16,
                        8,
                        "Maximum number of entries in case of circular buffers",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaxEntryLoop",
                        "Long64_t",
                        16,
                        8,
                        "Maximum number of entries to process",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fMaxVirtualSize",
                        "Long64_t",
                        16,
                        8,
                        "Maximum total size of buffers kept in memory",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fAutoSave",
                        "Long64_t",
                        16,
                        8,
                        "Autosave tree when fAutoSave entries written or -fAutoSave (compressed) bytes produced",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fAutoFlush",
                        "Long64_t",
                        16,
                        8,
                        "Auto-flush tree when fAutoFlush entries written or -fAutoFlush (compressed) bytes produced",
                    ),
                ),
                TStreamerBasicType(
                    _el(
                        "fEstimate",
                        "Long64_t",
                        16,
                        8,
                        "Number of entries to estimate histogram limits",
                    ),
                ),
                TStreamerBasicPointer(
                    _el(
                        "fClusterRangeEnd",
                        "Long64_t*",
                        56,
                        8,
                        "[fNClusterRange] Last entry of a cluster range.",
                    ),
                    20,
                    "fNClusterRange",
                    "TTree",
                ),
                TStreamerBasicPointer(
                    _el(
                        "fClusterSize",
                        "Long64_t*",
                        56,
                        8,
                        "[fNClusterRange] Number of entries in each cluster for a given range.",
                    ),
                    20,
                    "fNClusterRange",
                    "TTree",
                ),
                TStreamerObjectAny(
                    _el(
                        "fIOFeatures",
                        "ROOT::TIOFeatures",
                        62,
                        1,
                        "IO features to define for newly-written baskets and branches.",
                    ),
                ),
                TStreamerObject(_el("fBranches", "TObjArray", 61, 64, "List of Branches")),
                TStreamerObject(
                    _el(
                        "fLeaves",
                        "TObjArray",
                        61,
                        64,
                        "Direct pointers to individual branch leaves",
                    ),
                ),
                TStreamerObjectPointer(
                    _el(
                        "fAliases",
                        "TList*",
                        64,
                        8,
                        "List of aliases for expressions based on the tree branches.",
                    ),
                ),
                TStreamerObjectAny(
                    _el("fIndexValues", "TArrayD", 62, 24, "Sorted index values")
                ),
                TStreamerObjectAny(
                    _el("fIndex", "TArrayI", 62, 24, "Index of sorted values")
                ),
                TStreamerObjectPointer(
                    _el(
                        "fTreeIndex",
                        "TVirtualIndex*",
                        64,
                        8,
                        "Pointer to the tree Index (if any)",
                    ),
                ),
                TStreamerObjectPointer(
                    _el("fFriends", "TList*", 64, 8, "pointer to list of friend elements")
                ),
                TStreamerObjectPointer(
                    _el(
                        "fUserInfo",
                        "TList*",
                        64,
                        8,
                        "pointer to a list of user objects associated to this Tree",
                    ),
                ),
                TStreamerObjectPointer(
                    _el(
                        "fBranchRef",
                        "TBranchRef*",
                        64,
                        8,
                        "Branch supporting the TRefTable (if any)",
                    ),
                ),
            ],
        ),
    )

    push!(
        v,
        TStreamerInfo(
            "TVirtualStreamerInfo",
            6;
            checksum=0x44d1e2a1,
            elems=[
                TStreamerBase(
                    _el(
                        "TNamed",
                        "BASE",
                        67,
                        0,
                        "The basis for a named object (name, title)";
                        maxidx=(0, -541636036, 0, 0, 0),
                    ),
                    1,
                ),
            ],
        ),
    )

    return v
end
