# Histograms, read out of a file ROOT wrote.
#
# The fixture is `test/data/hists/hists.root`, generated by
# `dev/gen_hist_fixtures.jl`, and the fills in it are regular enough that what
# every bin should hold can be stated here rather than transcribed: bin `i` of
# `h1f` was filled `i` times, cell `(x, y)` of `h2f` holds `100x + y`. Where a
# number could not be derived that way — the errors of a profile — it is ROOT's
# own answer, printed by the generator.

using TTree
using TTree.Bytes
using TTree.Objects

const HISTS = joinpath(@__DIR__, "..", "data", "hists", "hists.root")

@testset "objects: histograms" begin
    @testset "TAxis" begin
        a = TAxis(4, 0.0, 2.0)
        @test nbins(a) == 4
        @test binedges(a) == [0.0, 0.5, 1.0, 1.5, 2.0]
        @test bincenters(a) == [0.25, 0.75, 1.25, 1.75]
        @test binwidth(a, 1) == 0.5
        @test binlowedge(a, 3) == 1.0
        # ROOT's bin numbering, which the underflow makes one-based-with-a-zero.
        @test Objects.findbin(a, -1.0) == 0
        @test Objects.findbin(a, 0.0) == 1
        @test Objects.findbin(a, 1.9) == 4
        @test Objects.findbin(a, 2.0) == 5
        @test Objects.findbin(a, 99.0) == 5

        v = TAxis([0.0, 1.0, 3.0, 6.0])
        @test nbins(v) == 3
        @test binedges(v) == [0.0, 1.0, 3.0, 6.0]
        @test binwidth(v, 2) == 2.0
        @test Objects.findbin(v, 4.0) == 3

        @test_throws ArgumentError TAxis(0, 0.0, 1.0)
        @test_throws ArgumentError TAxis([1.0])

        b = reencode(a)
        @test nbins(b) == 4
        @test binedges(b) == binedges(a)
    end

    @testset "reading ROOT's own file" begin
        TTree.open(HISTS) do f
            h = f["h1f"]
            @test h isa TH1F
            @test Objects.name(h) == "h1f"
            @test Objects.title(h) == "fixed bins"
            # One underflow, two overflows, and bin i filled i times.
            @test entries(h) == 58
            @test length(bincontents(h)) == 12
            @test bincontents(h) == Float32[1; 1:10; 2]
            @test binedges(h) == collect(0.0:1.0:10.0)
            # No `Sumw2`, so ROOT returns the root of the count.
            @test binerrors(h)[2] ≈ 1.0
            @test binerrors(h)[11] ≈ sqrt(10)

            # Weight 2 ten times, with the squared weights kept: the content is
            # 2 and the error is 2, not √2.
            d = f["h1d"]
            @test d isa TH1D
            @test entries(d) == 10
            @test sum(bincontents(d)) == 20
            @test binerrors(d)[2] ≈ 2.0

            i = f["h1i"]
            @test i isa TH1I
            @test bincontents(i) == Int32[0, 1000, 2000, 3000, 4000, 5000, 0]
            @test binerrors(i)[2] ≈ sqrt(1000)

            # `ClassDef(TH1L, 0)`: the version on disk is a checksum rather than
            # a number, and the contents do not fit in an Int32.
            l = f["h1l"]
            @test l isa TH1L
            @test eltype(bincontents(l)) === Int64
            @test bincontents(l) ==
                Int64[0, 5_000_000_000, 10_000_000_000, 15_000_000_000, 20_000_000_000, 0]

            # Variable bins: the edges come from fXbins, not from fXmin/fXmax.
            v = f["hvar"]
            @test binedges(v) == [0.0, 1.0, 3.0, 6.0, 10.0]
            @test bincontents(v) == [0, 1, 2, 3, 4, 0]
            @test binwidth(axis(v), 4) == 4.0

            # An alphanumeric axis, whose labels are a THashList of TObjString.
            lab = f["hlab"]
            @test binlabels(lab) == ["alpha", "beta", "gamma"]
            @test bincontents(lab) == Float32[0, 1, 2, 3, 0]
            @test binlabels(f["h1f"]) == String[]
        end
    end

    @testset "two and three dimensions" begin
        TTree.open(HISTS) do f
            h = f["h2f"]
            @test h isa TH2F
            @test nbins(h, :x) == 3
            @test nbins(h, :y) == 4
            c = bincontents(h)
            @test size(c) == (5, 6)
            # Cell (x, y) holds 100x + y, so x running fastest is visible: a
            # reader that transposed the array would find 100y + x here.
            for ix in 1:3, iy in 1:4
                @test c[ix + 1, iy + 1] == 100 * ix + iy
            end
            @test sum(c) == 2430
            @test all(iszero, c[1, :])
            @test all(iszero, c[:, 1])

            d = f["h2d"]
            @test entries(d) == 12
            @test sum(bincontents(d)) == 12

            t = f["h3d"]
            @test t isa TH3D
            @test (nbins(t, :x), nbins(t, :y), nbins(t, :z)) == (2, 3, 4)
            c3 = bincontents(t)
            @test size(c3) == (4, 5, 6)
            for ix in 1:2, iy in 1:3, iz in 1:4
                @test c3[ix + 1, iy + 1, iz + 1] == 10000 * ix + 100 * iy + iz
            end
            @test sum(c3) == 364860
        end
    end

    @testset "profiles" begin
        TTree.open(HISTS) do f
            p = f["prof"]
            @test p isa TProfile
            @test entries(p) == 8
            # Bin i was filled with i-1 and i+1, so it holds their mean — not
            # the sum of 2i that is actually on disk.
            @test bincontents(p) == [0, 1, 2, 3, 4, 0]
            @test binentries(p) == [0, 2, 2, 2, 2, 0]
            @test bineffentries(p) == [0, 2, 2, 2, 2, 0]
            # ROOT's GetBinError for the same bin: σ/√neff = 1/√2.
            @test binerrors(p)[2] ≈ 1 / sqrt(2)
            @test binerrors(p)[1] == 0
            @test p.errormode == Objects.ERRORMEAN

            q = f["prof2"]
            @test q isa TProfile2D
            c = bincontents(q)
            @test size(c) == (4, 5)
            for ix in 1:2, iy in 1:3
                @test c[ix + 1, iy + 1] ≈ 10 * ix + iy
            end
            @test sum(c) ≈ 102
            @test binerrors(q)[2, 2] ≈ 1 / sqrt(2)
        end
    end

    @testset "round-trip through this package's writer" begin
        TTree.open(HISTS) do f
            for nm in (
                "h1f",
                "h1d",
                "h1i",
                "h1l",
                "hvar",
                "hlab",
                "h2f",
                "h2d",
                "h3d",
                "prof",
                "prof2",
            )
                a = f[nm]
                b = reencode(a)
                @test typeof(b) === typeof(a)
                @test Objects.name(b) == Objects.name(a)
                @test entries(b) == entries(a)
                @test bincontents(b) == bincontents(a)
                @test binerrors(b) ≈ binerrors(a)
                @test binedges(b) == binedges(a)
                @test binlabels(b) == binlabels(a)
            end
        end
    end

    @testset "building and filling" begin
        h = TH1D("h", "made here", 4, 0.0, 4.0)
        @test length(bincontents(h)) == 6
        @test all(iszero, bincontents(h))
        for _ in 1:3
            push!(h, 1.5)
        end
        push!(h, -1.0)          # underflow
        push!(h, 9.0)           # overflow
        push!(h, 2.5, 4.0)      # weighted
        @test bincontents(h) == [1, 0, 3, 4, 0, 1]
        # ROOT counts every fill as one entry, weighted or not, but leaves the
        # under- and overflow out of the sums.
        @test entries(h) == 6
        @test histcore(h).tsumw == 7
        @test histcore(h).tsumwx ≈ 3 * 1.5 + 4 * 2.5

        # `Sumw2` after the fact takes what is there to have been unit-weighted,
        # so the errors it reports are unchanged until the next weighted fill.
        e = copy(binerrors(h))
        Objects.sumw2!(h)
        @test binerrors(h) ≈ e

        w = TH1D("w", "weighted", 2, 0.0, 2.0)
        Objects.sumw2!(w)
        push!(w, 0.5, 3.0)
        @test binerrors(w)[2] ≈ 3.0

        v = TH1F("v", "variable", [0.0, 1.0, 4.0])
        push!(v, 3.0)
        @test bincontents(v) == Float32[0, 0, 1, 0]

        h2 = TH2D("h2", "2d", 2, 0.0, 2.0, 3, 0.0, 3.0)
        push!(h2, 0.5, 2.5)
        push!(h2, 0.5, 2.5, 2.0)
        @test bincontents(h2)[2, 4] == 3
        @test entries(h2) == 2
        @test sum(bincontents(h2)) == 3

        # A base class holds no cells of its own; asking is a mistake rather
        # than an empty answer.
        @test_throws ArgumentError bincontents(TH1())
        @test_throws ArgumentError bincontents(TH2())
        @test_throws ArgumentError axis(h, :w)
    end

    @testset "a histogram written by this package reads back through a file" begin
        mktempdir() do dir
            path = joinpath(dir, "out.root")
            h = TH1F("written", "by TTree.jl", 5, 0.0, 5.0)
            for i in 1:5, _ in 1:i
                push!(h, i - 0.5)
            end
            g = TGraph("g", "a graph", [1.0, 2.0, 3.0], [4.0, 5.0, 6.0])
            TTree.create(path) do f
                write!(f, "written", h)
                write!(f, "g", g)
            end

            TTree.open(path) do f
                b = f["written"]
                @test b isa TH1F
                @test Objects.title(b) == "by TTree.jl"
                @test bincontents(b) == Float32[0, 1, 2, 3, 4, 5, 0]
                @test entries(b) == 15
                @test binedges(b) == collect(0.0:1.0:5.0)
                x, y = points(f["g"])
                @test x == [1.0, 2.0, 3.0]
                @test y == [4.0, 5.0, 6.0]
            end
        end
    end
end
